### PR TITLE
fix(internal/genclient): use service config name

### LINKED ISSUE #38: extract the service name from proto or service config
https://github.com/googleapis/google-cloud-rust/blob/77720dee3887853cc65bf31c90ce887b6e629976/generator/src/genclient/translator/protobuf/protobuf.go#L65-L66

### PR DESCRIPTION
**Pull request by julieqiu**
Fixes #38

### CODE REVIEW

File: generator/internal/genclient/translator/protobuf/protobuf.go [hunk 1]
```diff
@@ -55,29 +55,30 @@ type Options struct {
...
 func Translate(req *pluginpb.CodeGeneratorRequest, opts *Options) (*genclient.GenerateRequest, error) {
-	api := makeAPI(req)
-
 	codec, err := language.NewCodec(opts.Language)
 	if err != nil {
 		return nil, err
 	}
+	var name string
+	if opts.ServiceConfig != nil {
+		name = opts.ServiceConfig.Name
```
Comment (coryan) [inline generator/internal/genclient/translator/protobuf/protobuf.go:64]: I think this is an improvement, but I am not sure it is exactly what we want.  For our test service that would be "secretmanager.googleapis.com".  Or maybe we want this, but we strip out the `.googleapis.com` to create crate names and the such.

No action required.

**Review by coryan — APPROVED** [review]

File: generator/internal/genclient/translator/protobuf/protobuf.go (hunk 1 above)
Comment (julieqiu) [reply generator/internal/genclient/translator/protobuf/protobuf.go:64]: Ack that's a good point.
