### PR TITLE
test(gax-internal): deflake metrics test

### LINKED ISSUE #4916: Flake in duration metrics test
I got this error:

```
thread 'observability::client_signals::duration_metric::tests::global_record_ok' (35427) panicked at src/gax-internal/src/observability/client_signals/duration_metric.rs:185:9:
expected a single data point, histo=Histogram { data_points: [HistogramDataPoint { attributes: [KeyValue { key: Static("http.response.status_code"), value: I64(200) }, KeyValue { key: Static("rpc.method"), value: String(Static("test-method")) }, KeyValue { key: Static("rpc.response.status_code"), value: String(Static("OK")) }, KeyValue { key: Static("rpc.system.name"), value: String(Static("http")) }, KeyValue { key: Static("url.domain"), value: String(Static("example.com")) }, KeyValue { key: Static("url.template"), value: String(Static("/v1/projects/{}:test_method")) }], count: 1, bounds: [0.0, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0, 60.0, 300.0, 900.0, 3600.0], bucket_counts: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], min: Some(0.75), max: Some(0.75), sum: 0.75, exemplars: [] }, HistogramDataPoint { attributes: [KeyValue { key: Static("rpc.method"), value: String(Static("test-method")) }, KeyValue { key: Static("rpc.response.status_code"), value: String(Static("NOT_FOUND")) }, KeyValue { key: Static("rpc.system.name"), value: String(Static("http")) }, KeyValue { key: Static("url.domain"), value: String(Static("example.com")) }, KeyValue { key: Static("url.template"), value: String(Static("/v1/projects/{}:test_method")) }], count: 2, bounds: [0.0, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0, 60.0, 300.0, 900.0, 3600.0], bucket_counts: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], min: Some(0.0), max: Some(0.0), sum: 0.0, exemplars: [] }], start_time: SystemTime { tv_sec: 1772751781, tv_nsec: 926308283 }, time: SystemTime { tv_sec: 1772751782, tv_nsec: 64266409 }, temporality: Cumulative }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Seems like the counter is "2" when the test expects "1".  I need to disable the test and then fix it.

### PR DESCRIPTION
**Pull request by coryan**
Relax one of the test conditions to make the test not fail. Other tests cover the "value must be strictly 1" case, we can relax this test to be "value must be at least 1".

Fixes #4916

### CODE REVIEW

File: src/gax-internal/src/observability/client_signals/duration_metric.rs [hunk 1]
```diff
@@ -179,15 +178,21 @@ mod tests {
...
-        metric.record_ok(&start);
+        let error = Error::http(408, http::HeaderMap::new(), bytes::Bytes::new());
+        metric.record_error(&start, &error);
         provider.force_flush()?;
         let metrics = exporter.get_finished_metrics()?;
         check_scope(&metrics);
         check_data(
             &metrics,
+            // We cannot predict the exact value as other tests in the crate may
+            // be using the same same global meter provider. The remaining
```
Comment (dbolduc) [inline src/gax-internal/src/observability/client_signals/duration_metric.rs]: s/same same/same/

Comment (coryan) [reply src/gax-internal/src/observability/client_signals/duration_metric.rs]: Fixed, thanks.
