### PR TITLE
cleanup(rustdocfx): enable and fix go lints

### LINKED ISSUE #3219: [docfx] Add standard golang tests
Things like formatting, find unused functions, find unused args, etc.

### PR DESCRIPTION
**Pull request by coryan**
Fixes #3219

### CODE REVIEW

File: doc/rustdocfx/generate.go [hunk 1]
```diff
@@ -320,22 +305,6 @@ func processImplementation(c *crate, id string, page *docfxManagedReference, par
 	return nil
 }
 
-func newDocfxItemFromAssocConst(c *crate, parent *docfxItem, id string) (*docfxItem, error) {
```
Comment (dbolduc) [inline doc/rustdocfx/generate.go:323]: I take it these removed functions are unused code?

cc: @PhongChuong to add them back if they are needed.

**Review by dbolduc — APPROVED** [review]

File: doc/rustdocfx/generate.go (hunk 1 above)
Comment (PhongChuong) [reply doc/rustdocfx/generate.go:323]: Yes.
We trimmed out some features earlier.
Thanks for the heads up.

**Review by PhongChuong — APPROVED** [review]
