### PR TITLE
fix(auth): generate private key for test from primes

### LINKED ISSUE #2121: Flakes in `test credentials::service_account::test::*`
```
test credentials::service_account::test::get_service_account_token_with_audience has been running for over 60 seconds
2025-05-13T14:30:19.029398Z ERROR cargo_tarpaulin: Failed to run tests: Error: Timed out waiting for test response
Error: "Failed to run tests: Error: Timed out waiting for test response"
```

https://github.com/googleapis/google-cloud-rust/actions/runs/14999187000/job/42141254733?pr=2120

### PR DESCRIPTION
**Pull request by sai-sunder-s**
Attempting to fix #2121 by using pre-generated primes to speed up key generation.

### CODE REVIEW

File: src/auth/src/credentials.rs [hunk 1]
```diff
@@ -633,9 +634,19 @@ mod test {
...
+        let p = BigUint::parse_bytes(p_str.as_bytes(), 10).expect("Failed to parse prime P");
+        let q = BigUint::parse_bytes(q_str.as_bytes(), 10).expect("Failed to parse prime Q");
+        let public_exponent =
+            BigUint::parse_bytes(e_str.as_bytes(), 10).expect("Failed to parse public exponent");
+
+        // Create the RsaPrivateKey from pre-defined primes
+        let priv_key = RsaPrivateKey::from_primes(vec![p, q], public_exponent)
+            .expect("Failed to create RsaPrivateKey from primes");
+
         priv_key
```
Comment (dbolduc) [inline src/auth/src/credentials.rs:650]: We are still generating a key here:

https://github.com/googleapis/google-cloud-rust/blob/474d40114b59f2dcccca1e72469e1110685a57c1/src/auth/src/credentials/service_account.rs#L582

I think my `LazyLock` PR missed the point. I had two separate `LazyLock`s for PKCS1 and PKCS8 keys, but I really should have had one `LazyLock<RsaPrivateKey>` that we call `to_pkcs8_pem` or `to_pkcs1_pem` on.

Do you mind fixing this?

Comment (sai-sunder-s) [reply src/auth/src/credentials.rs]: Done

**Review by dbolduc — APPROVED** [review]
This is cool. I am not going to ask where/how you found those big primes.
