### PR TITLE
fix(pubsub): batch nacks on shutdown to respect service limits

### LINKED ISSUE #4847: Subscriber nacks on shutdown need to respect quota limits
https://github.com/googleapis/google-cloud-rust/blob/df77ebc841b24f23dc52cd747e07bc82e61975ec/src/pubsub/src/subscriber/lease_state.rs#L221

While `self.to_nack.len() <= ACK_IDS_PER_RPC`, that stops being true when we extend it by the messages currently under lease management.

We need to break this up into batches.

### PR DESCRIPTION
**Pull request by suzmue**
Ensure that when the Pub/Sub subscriber shuts down, it does not exceed the MAX_IDS_PER_RPC limit (2,500 IDs) when sending negative acknowledgments (nacks) for messages still under lease management. It also refactors the lease eviction logic to reduce code duplication.

Fixes #4847

### CODE REVIEW

File: src/pubsub/src/subscriber/lease_state/at_least_once.rs [hunk 1]
```diff
@@ -288,15 +289,80 @@ mod tests {
...
                 under_lease: Vec::new(),
                 to_ack: test_ids(0..10),
                 to_nack: test_ids(10..30),
             },
+            Leases {
+                to_ack,
+                to_nack: to_nack.into_iter().flatten().collect(),
+                ..Default::default()
+            }
+        );
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state/at_least_once.rs]: Consider:

```rs
assert_eq!(to_ack, test_ids(0..10));
assert_eq!(to_nack, vec![test_ids(10..30)]);
```

No need to put them back in a `Leases` object

File: src/pubsub/src/subscriber/lease_state/at_least_once.rs [hunk 2]
```diff
@@ -288,15 +289,80 @@ mod tests {
...
+                under_lease: Vec::new(),
+                to_ack: test_ids(0..10),
+                to_nack: test_ids(10..MAX_IDS_PER_RPC * 3),
+            },
+            Leases {
+                to_ack: to_ack,
+                to_nack: to_nack.into_iter().flatten().collect(),
+                ..Default::default()
+            },
+        );
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state/at_least_once.rs]: Your call on how to make the `to_nack` comparison most readable. Not sure this is any better, but could do something like:

```rs
struct NackBatches {
  counts: Vec<usize>,
  ack_ids: Vec<String>,
}

fn flatten(to_nacks: Vec<Vec<String>>) -> NackBatches {
  NackBatches {
    counts: to_nacks.map(|v| v.len()).collect(),
    ack_ids: sorted(to_nacks.into_iter().flatten().collect()),
  }
}
```

then:

```rs
let got = flatten(to_nack);
assert_eq!(got.counts, vec![MAX_IDS_PER_RPC, MAX_IDS_PER_RPC, MAX_IDS_PER_RPC - 10]);
assert_eq!(got.ack_ids, test_ids(10..MAX_IDS_PER_RPC * 3));
```

🤷

File: src/pubsub/src/subscriber/lease_state/exactly_once.rs [hunk 3]
```diff
@@ -664,13 +665,94 @@ mod tests {
...
                 under_lease: Vec::new(),
                 to_ack: Vec::new(),
                 to_nack: test_ids(1..4),
             },
+            Leases {
+                to_ack,
+                to_nack: to_nack.into_iter().flatten().collect(),
+                ..Default::default()
+            }
+        );
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state/exactly_once.rs]: same.

File: src/pubsub/src/subscriber/lease_state/exactly_once.rs [hunk 4]
```diff
@@ -664,13 +665,94 @@ mod tests {
...
+        let (result_tx, result_rx2) = channel();
+        leases.add(
+            test_id(2),
+            ExactlyOnceInfo {
+                receive_time: Instant::now(),
+                result_tx,
+                pending: false,
+            },
+        );
+
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state/exactly_once.rs]: Checking the results on the channel is covered by the `evict()` test. No need to check it in the batching test.

File: src/pubsub/src/subscriber/lease_state/exactly_once.rs [hunk 5]
```diff
@@ -664,13 +665,94 @@ mod tests {
...
+        // Add MAX_IDS_PER_RPC + 10 messages under lease management. Nack some and evict.
+        for i in 3..MAX_IDS_PER_RPC + 20 {
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state/exactly_once.rs]:
```suggestion
        for i in 0..MAX_IDS_PER_RPC + 20 {
```

File: src/pubsub/src/subscriber/lease_state/exactly_once.rs [hunk 6]
```diff
@@ -664,13 +665,94 @@ mod tests {
...
+            leases.add(test_id(i), test_info());
+            if i % 2 == 0 {
+                leases.nack(test_id(i));
+            }
+        }
+        let (to_ack, to_nack) = leases.evict_and_drain();
+        assert_eq!(to_nack.len(), 2);
+        assert_eq!(to_nack[0].len(), MAX_IDS_PER_RPC as usize);
+        assert_eq!(to_nack[1].len(), 19);
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state/exactly_once.rs]: ... then this is 20, not 19. Less mental math the reader needs to do.

File: src/pubsub/src/subscriber/lease_state/at_least_once.rs (hunk 1 above)
Comment (dbolduc) [reply src/pubsub/src/subscriber/lease_state/at_least_once.rs]: Oh, now I remember. The `impl PartialEq` for this thing sorts the lists for us. Yuck.

File: src/pubsub/src/subscriber/lease_state.rs [hunk 7]
```diff
@@ -34,6 +34,18 @@ use tokio_util::task::TaskTracker;
 // https://docs.cloud.google.com/pubsub/quotas
 const MAX_IDS_PER_RPC: usize = 2500;
 
+// Helper function to chunk nack ids into chunks of MAX_IDS_PER_RPC.
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state.rs]: maybe "ack IDs to nack" instead of "nack ids" ?

File: src/pubsub/src/subscriber/lease_state/exactly_once.rs [hunk 8]
```diff
@@ -127,17 +127,18 @@ impl Leases {
     }
 
     /// Nacks all messages under lease management that have not been acked by
-    /// the application.
+    /// the application and drains all messages from the lease state.
     ///
     /// Called during shutdown, if configured to `NackImmediately`.
-    pub fn evict(&mut self) {
+    pub fn evict_and_drain(&mut self) -> (Vec<String>, Vec<Vec<String>>) {
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state/exactly_once.rs]: nit: I think we are done with the struct after this, so it should be :  `evict_and_drain(mut self)`

File: src/pubsub/src/subscriber/lease_state/exactly_once.rs [hunk 9]
```diff
@@ -127,17 +127,18 @@ impl Leases {
...
         let under_lease = std::mem::take(&mut self.under_lease);
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state/exactly_once.rs]: and no need to replace this. we can just move it out.

File: src/pubsub/src/subscriber/lease_state/at_least_once.rs [hunk 10]
```diff
@@ -99,12 +99,13 @@ impl Leases {
     }
 
     /// Nacks all messages under lease management that have not been acked by
-    /// the application.
+    /// the application and drains all messages from the lease state.
     ///
     /// Called during shutdown, if configured to `NackImmediately`.
-    pub fn evict(&mut self) {
+    pub fn evict_and_drain(&mut self) -> (Vec<String>, Vec<Vec<String>>) {
         let under_lease = std::mem::take(&mut self.under_lease);
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state/at_least_once.rs]: same

File: src/pubsub/src/subscriber/lease_state/at_least_once.rs [hunk 11]
```diff
@@ -335,34 +319,19 @@ mod tests {
...
-                to_nack: test_ids(10..MAX_IDS_PER_RPC * 3),
-            },
-            Leases {
-                to_ack: to_ack,
-                to_nack: to_nack.into_iter().flatten().collect(),
-                ..Default::default()
-            },
-        );
+        to_ack.sort();
+        assert_eq!(to_ack, test_ids(0..10));
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state/at_least_once.rs]: nit: I think I have a shorthand to sort these containers.

```rs
        assert_eq!(sorted(&to_ack), test_ids(0..10));
```

File: src/pubsub/src/subscriber/lease_state/at_least_once.rs [hunk 12]
```diff
@@ -102,10 +102,9 @@ impl Leases {
     /// the application and drains all messages from the lease state.
     ///
     /// Called during shutdown, if configured to `NackImmediately`.
-    pub fn evict_and_drain(&mut self) -> (Vec<String>, Vec<Vec<String>>) {
-        let under_lease = std::mem::take(&mut self.under_lease);
-        self.to_nack.extend(under_lease.into_keys());
-        super::batch_drained(self.drain())
+    pub fn evict_and_drain(mut self) -> (Vec<String>, Vec<Vec<String>>) {
+        self.to_nack.extend(self.under_lease.into_keys());
+        (self.to_ack, super::batch_drained(self.to_nack))
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state/at_least_once.rs]: comment: I think it is cleaner now that the common fn only takes a `Vec<String>` instead of handling the tuple. 👍

File: src/pubsub/src/subscriber/lease_state/at_least_once.rs (hunk 11 above)
Comment (dbolduc) [reply src/pubsub/src/subscriber/lease_state/at_least_once.rs]: here and elsewhere.

File: src/pubsub/src/subscriber/lease_state.rs [hunk 13]
```diff
@@ -34,16 +34,12 @@ use tokio_util::task::TaskTracker;
...
-    (
-        drained.0, // acks
-        drained
-            .1
-            .chunks(MAX_IDS_PER_RPC)
-            .map(|c| c.to_vec())
-            .collect(), // nacks
-    )
+// Helper function to chunk ack ids to nack into chunks of MAX_IDS_PER_RPC.
+fn batch_drained(ack_ids: Vec<String>) -> Vec<Vec<String>> {
```
Comment (dbolduc) [inline src/pubsub/src/subscriber/lease_state.rs]: naming nit: maybe just `batch` now?

**Comment by dbolduc** [comment]
Thanks for the fix!

File: src/pubsub/src/subscriber/lease_state/at_least_once.rs (hunk 1 above)
Comment (suzmue) [reply src/pubsub/src/subscriber/lease_state/at_least_once.rs]: Yeah this is why I used it. It is kind of weird now that the lease is consumed so I just updated the tests to sort.

File: src/pubsub/src/subscriber/lease_state/exactly_once.rs (hunk 5 above)
Comment (suzmue) [reply src/pubsub/src/subscriber/lease_state/exactly_once.rs]: done.

File: src/pubsub/src/subscriber/lease_state/exactly_once.rs (hunk 6 above)
Comment (suzmue) [reply src/pubsub/src/subscriber/lease_state/exactly_once.rs]: done.

File: src/pubsub/src/subscriber/lease_state.rs (hunk 7 above)
Comment (suzmue) [reply src/pubsub/src/subscriber/lease_state.rs]: done.

File: src/pubsub/src/subscriber/lease_state/exactly_once.rs (hunk 8 above)
Comment (suzmue) [reply src/pubsub/src/subscriber/lease_state/exactly_once.rs]: done.

File: src/pubsub/src/subscriber/lease_state/exactly_once.rs (hunk 9 above)
Comment (suzmue) [reply src/pubsub/src/subscriber/lease_state/exactly_once.rs]: done.

File: src/pubsub/src/subscriber/lease_state/at_least_once.rs (hunk 10 above)
Comment (suzmue) [reply src/pubsub/src/subscriber/lease_state/at_least_once.rs]: done.

File: src/pubsub/src/subscriber/lease_state/at_least_once.rs (hunk 12 above)
Comment (suzmue) [reply src/pubsub/src/subscriber/lease_state/at_least_once.rs]: Yeah, it was a convenience to save typing when forwarding the result of drain, but since we can take things directly was able to simplify.

File: src/pubsub/src/subscriber/lease_state/at_least_once.rs (hunk 11 above)
Comment (suzmue) [reply src/pubsub/src/subscriber/lease_state/at_least_once.rs]: done. thanks!

File: src/pubsub/src/subscriber/lease_state.rs (hunk 13 above)
Comment (suzmue) [reply src/pubsub/src/subscriber/lease_state.rs]: done

**Review by dbolduc — APPROVED** [review]
