### PR TITLE
fix(auth): sync claim/token times in SA creds

### LINKED ISSUE #733: Mismatched expiration time in service account credentials
This is wrong:

https://github.com/googleapis/google-cloud-rust/blob/d1348119749a52e9bdc48267eca3d1746d330250/src/auth/src/credentials/service_account_credential.rs#L89

The expiration time should match the expiration time in the credentials, which is set to `now - fudge + default`.  And there are two separate calls to `utc_now()` which may return different values.

### PR DESCRIPTION
**Pull request by dbolduc**
Fixes #733 

Make sure the token's `expires_at` time matches the `exp` field in the claim.

We drop the `JwsClaimsBuilder` and do any defaulting in `service_account_credential.rs`. Note that the `exp` and `iat` fields are required, so they are probably better represented as `OffsetDateTime` than `Option<OffsetDateTime>`.

### CODE REVIEW

File: src/auth/src/credentials/util/jws.rs [hunk 1]
```diff
@@ -14,7 +14,6 @@
 
 use crate::credentials::CredentialError;
 use crate::credentials::Result;
-use derive_builder::Builder;
```
Comment (coryan) [inline src/auth/src/credentials/util/jws.rs:17]: Thanks. I think there is an unused dependency in `src/auth/Cargo.toml` now.

File: src/auth/src/credentials/service_account_credential.rs [hunk 2]
```diff
@@ -66,11 +68,17 @@ impl TokenProvider for ServiceAccountTokenProvider {
...
+        let exp = now + DEFAULT_TOKEN_TIMEOUT;
+        let claims = JwsClaims {
+            iss: self.service_account_info.client_email.clone(),
+            scope: Some(DEFAULT_SCOPES.map(|s| s.to_string()).to_vec()),
+            aud: None,
+            exp,
+            iat: now,
+            typ: None,
+            sub: None,
+        };
```
Comment (coryan) [inline src/auth/src/credentials/service_account_credential.rs:81]: Alternatively, you could create a `JwsClaims::new(now: OffsetDateTime) -> Self ` function.

File: src/auth/src/credentials/util/jws.rs [hunk 3]
```diff
@@ -29,32 +28,28 @@ pub(crate) const CLOCK_SKEW_FUDGE: Duration = Duration::from_secs(10);
 pub(crate) const DEFAULT_TOKEN_TIMEOUT: Duration = Duration::from_secs(3600);
 
 /// JSON Web Signature for a token.
-#[derive(Clone, Serialize, Default, Builder)]
-#[builder(setter(into, strip_option), default)]
-pub struct JwsClaims<'a> {
-    pub iss: &'a str,
+#[derive(Serialize)]
+pub struct JwsClaims {
+    pub iss: String,
```
Comment (coryan) [inline src/auth/src/credentials/util/jws.rs:33]: I like the simplicity of using `String`.  It is more expensive, but this function will be called like once per hour so we should not complicate things too much in search of small performance improvements.

File: src/auth/src/credentials/util/jws.rs [hunk 4]
```diff
@@ -116,44 +112,30 @@ mod tests {
         )
         .unwrap();
 
-        // 5 seconds is like 640KiB, good enough for everybody
```
Comment (coryan) [inline src/auth/src/credentials/util/jws.rs:119]: 🎉

**Review by coryan — COMMENTED** [review]
Please remove any unnecessary dependencies and then ship it!

File: src/auth/src/credentials/util/jws.rs (hunk 3 above)
Comment (dbolduc) [reply src/auth/src/credentials/util/jws.rs:33]: Ack

File: src/auth/src/credentials/util/jws.rs (hunk 1 above)
Comment (dbolduc) [reply src/auth/src/credentials/util/jws.rs:17]: Still used elsewhere:

https://github.com/googleapis/google-cloud-rust/blob/31c8a5eb590cf8908453ddaa14fc35cfb32220fb/src/auth/src/credentials/service_account_credential.rs#L40

**Review by sai-sunder-s — APPROVED** [review]
