### PR TITLE
fix(secret_manager): garbage collect locational secrets in integration tests

### LINKED ISSUE #4349: Integration tests are not garbage collecting locational secrets
Our integration tests create locational secrets with dummy data, but we don't seem to garbage collect them correctly:

Image

Probably some silly mistake in the garbage collection loops?

### PR DESCRIPTION
**Pull request by haphungw**
Fixes #4349

The stale secrets were not correctly removed since wrong arguments were passed into `delete_secret_by_project_and_location_and_secret`. This fix parses the secret name to properly delete stale secrets.

### CODE REVIEW

File: tests/integration/src/secret_manager/openapi_locational.rs [hunk 1]
```diff
@@ -399,12 +399,18 @@ async fn cleanup_stale_secrets(
 
     let pending = stale_secrets
         .iter()
-        .map(|secret_id| {
+        .map(|name| {
+            // format: projects/{project}/locations/{location}/secrets/{secret}
+            let parts: Vec<&str> = name.split('/').collect();
+            let project = parts[1];
+            let location = parts[3];
+            let secret = parts[5];
```
Comment (coryan) [inline tests/integration/src/secret_manager/openapi_locational.rs]: This will panic if the name is not in the right format:

https://doc.rust-lang.org/std/vec/struct.Vec.html#indexing

You may try something like:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=c1164c67bd2b89c1fcde61bcd31ed939

Which validates all the stuff and never panics.

File: tests/integration/src/secret_manager/openapi_locational.rs [hunk 2]
```diff
@@ -399,12 +399,18 @@ async fn cleanup_stale_secrets(
 
     let pending = stale_secrets
         .iter()
-        .map(|secret_id| {
+        .map(|name| {
+            // format: projects/{project}/locations/{location}/secrets/{secret}
+            let parts: Vec<&str> = name.split('/').collect();
```
Comment (coryan) [inline tests/integration/src/secret_manager/openapi_locational.rs]: Materializing the vector always makes me sad (an allocation that strictly we do not need).  But for test code, this is fine.

File: tests/integration/src/secret_manager/openapi_locational.rs [hunk 3]
```diff
@@ -419,3 +421,44 @@ async fn cleanup_stale_secrets(
 
     Ok(())
 }
+
+fn extract(name: &str) -> Result<(&str, &str, &str)> {
```
Comment (coryan) [inline tests/integration/src/secret_manager/openapi_locational.rs]: I was maybe too succinct in my playground example: 

```suggestion
fn parse_secret_name(name: &str) -> Result<(&str, &str, &str)> {
```

File: tests/integration/src/secret_manager/openapi_locational.rs [hunk 4]
```diff
@@ -419,3 +421,44 @@ async fn cleanup_stale_secrets(
...
+    #[test]
+    fn test_extract_invalid_name() {
+        let name = "invalid/format";
+        assert!(extract(name).is_err());
+    }
+
+    #[test]
+    fn test_extract_missing_parts() {
+        assert!(extract("projects/only-one").is_err());
+    }
```
Comment (coryan) [inline tests/integration/src/secret_manager/openapi_locational.rs]: Consider:


```suggestion
    #[test_case("invalid/format")]
    #[test_case("projects/only-one")]
    #[test_case("projects/p/locations/l/bad/s")]
    #[test_case("projects/p/bad/l/secrets/s")]
    #[test_case("bad/p/locations/l/secrets/s")]
    fn test_extract_invalid_name(input: &str) {
        let result = parse_secret_name(input);
        assert!(result.is_err(), "{result:?});
    }
```

File: tests/integration/src/secret_manager/openapi_locational.rs [hunk 5]
```diff
@@ -419,3 +421,44 @@ async fn cleanup_stale_secrets(
...
+            "secrets",
+            s,
+        ] => Ok((p, l, s)),
+        _ => Err(anyhow!("invalid secret name: {}", name)),
+    }
+}
+
+#[cfg(test)]
+mod tests {
+    use super::*;
```
Comment (coryan) [inline tests/integration/src/secret_manager/openapi_locational.rs:435]:
```suggestion
    use super::*;
    use test_case::test_case;
```

to use `#[test_case]` below.

File: tests/integration/src/secret_manager/openapi_locational.rs [hunk 6]
```diff
@@ -399,12 +400,13 @@ async fn cleanup_stale_secrets(
 
     let pending = stale_secrets
         .iter()
-        .map(|secret_id| {
+        .map(|name| {
+            let (project, location, secret) = extract(name).unwrap();
```
Comment (coryan) [inline tests/integration/src/secret_manager/openapi_locational.rs]: This still panics, no? Maybe something like (but move the function definition to the right place):

```rust
async fn delete_by_name(client: smo::client::SecretManagerService, &name: &str) -> anyhow::Result<()> {
    let (project, location, secret) = parse_secret_name(name)?;
    client.delete_secret_by_project_and_location_and_secret()
        .set_project(project)
        .set_location(location)
        .set_secret(secret)
        .with_idempotency(true)
        .send()
        .await?;    
    Ok(())
}

let pending = stale_secrets.iter().map(|name| delete_by_name(name));
```

Comment (coryan) [reply tests/integration/src/secret_manager/openapi_locational.rs]: Hmmm... now that I think about it, we don't need a function, I think an expression like this should work to:

```rust
let pending = stale_secrets.iter().map(|name| -> anyhow::Result<()> {
    let (project, location, secret) = parse_secret_name(name)?;
    client.delete_secret_by_project_and_location_and_secret()
        .set_project(project)
        .set_location(location)
        .set_secret(secret)
        .with_idempotency(true)
        .send()
        .await?;    
    Ok(())    
});
```

Your call.

Comment (haphungw) [reply tests/integration/src/secret_manager/openapi_locational.rs]: keeping it inline makes sense since it's only used once here. 
I wrapped it in an `async move` block to make the `.await` work inside the closure.

**Review by coryan — APPROVED** [review]
