### PR TITLE
test(auth): deflake jws test

### LINKED ISSUE #731: Flake in auth unit test
I think this is a flake:

test credentials::util::jws::tests::test_jws_claims_encode_defaults

https://github.com/googleapis/google-cloud-rust/actions/runs/12836529092/job/35798289382?pr=728#step:7:610

```
failures:

---- credentials::util::jws::tests::test_jws_claims_encode_defaults stdout ----
thread 'credentials::util::jws::tests::test_jws_claims_encode_defaults' panicked at src/auth/src/credentials/util/jws.rs:126:9:
assertion `left == right` failed
  left: Number(1737146733)
 right: 1737146734
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by coryan**
Fixes #731

### CODE REVIEW

**Review by codyoss — APPROVED** [review]

File: src/auth/src/credentials/util/jws.rs [hunk 1]
```diff
@@ -41,13 +48,7 @@ pub struct JwsClaims<'a> {
 
 impl JwsClaims<'_> {
     pub fn encode(&self) -> Result<String> {
```
Comment (dbolduc) [inline src/auth/src/credentials/util/jws.rs:50]: Did you consider `encode(&self, now: OffsetDateTime)` ?

I think that would lead to less "engineering" in the test.
