### PR TITLE
impl(storage): configurable buffered upload types

### LINKED ISSUE #2056: Automatically retry failed single-shot uploads
Subject to the conditional idempotency rules, we should retry any single-shot upload that fails, with all the right policies, of course.

### LINKED ISSUE #2709: Use resumable uploads for large `send_unbuffered() / send()` requests

### PR DESCRIPTION
**Pull request by coryan**
Switch the upload type based on the size of the payload. Small uploads
perform better when using single-shot uploads. Large uploads require
resumable uploads to keep the buffer size under control, and the extra
latency is not that bad in relative terms.

Fixes #2709, fixes #2056

### CODE REVIEW

File: src/storage/src/storage/upload_object/buffered.rs [hunk 1]
```diff
@@ -33,22 +33,16 @@ where
     /// # Ok(()) }
     /// ```
     pub async fn send(self) -> crate::Result<Object> {
-        let upload_url = self.start_resumable_upload().await?;
         // TODO(#2043) - make the threshold to use resumable uploads and the
         //    target size for each chunk configurable.
```
Comment (dbolduc) [inline src/storage/src/storage/upload_object/buffered.rs]: nit: stale comment

File: src/storage/src/storage/upload_object/buffered.rs [hunk 2]
```diff
@@ -33,22 +33,16 @@ where
...
-        if self.payload.lock().await.size_hint().0 > RESUMABLE_UPLOAD_QUANTUM as u64 {
+        let hint = self.payload.lock().await.size_hint().1;
+        if hint.is_some_and(|max| max >= self.options.resumable_upload_threshold as u64) {
```
Comment (dbolduc) [inline src/storage/src/storage/upload_object/buffered.rs]: Q: should the default for unknown-sized objects be resumable uploads? i.e. `s/is_some_and/is_none_or/`

File: src/storage/src/storage/upload_source.rs [hunk 3]
```diff
@@ -205,23 +214,84 @@ impl Seek for BytesSource {
     }
 }
 
+pub struct IterSource {
```
Comment (dbolduc) [inline src/storage/src/storage/upload_source.rs:217]: is this intentionally public?

File: src/storage/src/storage/upload_source.rs [hunk 4]
```diff
@@ -205,23 +214,84 @@ impl Seek for BytesSource {
...
+    fn size_hint(&self) -> (u64, Option<u64>) {
+        let s = self.contents.iter().fold(0_u64, |a, i| a + i.len() as u64);
+        (s, Some(s))
+    }
+}
+
+impl Seek for IterSource {
+    type Error = std::io::Error;
+    async fn seek(&mut self, offset: u64) -> std::result::Result<(), Self::Error> {
+        let mut current: VecDeque<_> = self.contents.iter().cloned().collect();
```
Comment (dbolduc) [inline src/storage/src/storage/upload_source.rs]: if this is a public type, this implementation should be more efficient. We only need to clone the chunks from `contents` which have already been consumed from `current`.

**Review by dbolduc — COMMENTED** [review]
Move `IterSource` back into `mod tests`?

File: src/storage/src/storage/upload_object/buffered.rs (hunk 1 above)
Comment (coryan) [reply src/storage/src/storage/upload_object/buffered.rs]: Fixed.

File: src/storage/src/storage/upload_object/buffered.rs (hunk 2 above)
Comment (coryan) [reply src/storage/src/storage/upload_object/buffered.rs]: D'oh! yes.

File: src/storage/src/storage/upload_source.rs (hunk 4 above)
Comment (coryan) [reply src/storage/src/storage/upload_source.rs]: Hmm... clone for `bytes::Bytes` is just incrementing a reference count, but sure.

File: src/storage/src/storage/upload_source.rs (hunk 3 above)
Comment (coryan) [reply src/storage/src/storage/upload_source.rs:217]: I think eventually it will need to be (to return `InsertPayload<IterSource>`, but let's leave it `pub(crate)` for now.

File: src/storage/src/storage/upload_source.rs (hunk 4 above)
Comment (dbolduc) [reply src/storage/src/storage/upload_source.rs]: My mistake, I forgot the clone was super cheap

**Review by dbolduc — APPROVED** [review]
