### PR TITLE
fix(storage): `send_buffered()` fails for some object sizes

### LINKED ISSUE #3608: Malformed header in ResumableUpload when ObjectSize is multiple of Buffer size and no size hint is provided
When performing a send_buffered request using a Payload providing no SizeHint, if the object size is a multiple of the buffer size, the request fails with a malformed "Content-Range" header.

#### Environment details

  - Programming language:Rust
  - OS:Linux
  - Language runtime version: 1.90 (2024)
  - Package version: 1.1.0

#### Steps to reproduce
You can find a reproducer code here : https://gist.github.com/dbrasseur-aneo/c2ee7e8ece49dd4fb82fea73a5f9f43c
  1. Create a Storage.write_object request
  2. Set the source as a stream with no size_hint (or a size_hint with no upper)
  3. use the send_buffered function to send the stream to an object
  4. If the object size is a multiple of the buffer size, a request is sent with a malformed "Content-Range" header, leading to the failure

#### Potential location of the issue
After doing some digging, the issue may stem from https://github.com/googleapis/google-cloud-rust/blob/main/src/storage/src/storage/perform_upload/buffered/progress.rs#L162 used here https://github.com/googleapis/google-cloud-rust/blob/main/src/storage/src/storage/perform_upload/buffered.rs#L120

When uploading the first buffer, it gives : "bytes 0-'buffsize-1'/*"
But on the last buffer it gives: "bytes 'objectsize'-'objectsize-1'/'objectsize'" (since n==0), which is invalid.

Thanks!

### PR DESCRIPTION
**Pull request by coryan**
If the upload size is unknown and the stream is closed at a multiple of the buffer size the client library needs to send a final `PUT` request without a payload. The `Content-Range` header was not formatted correctly in this case.

Fixes #3608

### CODE REVIEW

File: src/integration-tests/src/storage.rs [hunk 1]
```diff
@@ -253,7 +253,7 @@ pub async fn create_test_hns_bucket() -> Result<(StorageControl, Bucket)> {
 
 async fn client_for_create_bucket() -> Result<StorageControl> {
     let client = StorageControl::builder()
-        .with_tracing()
+        // .with_tracing()
```
Comment (dbolduc) [inline src/integration-tests/src/storage.rs]: delete or uncomment

File: src/integration-tests/src/storage/write_object.rs [hunk 2]
```diff
@@ -16,6 +16,18 @@ use crate::Result;
...
+    bucket_name: &str,
+) -> Result<()> {
+    // Run all the upload tests in parallel, using the same bucket.
+    // Creating a new bucket is rate-limited, and slow. Creating objects
+    // is relatively cheap.
+    let client = builder.build().await?;
+    repro_3608_buffered(&client, bucket_name).await?;
+    Ok(())
+}
+
```
Comment (dbolduc) [inline src/integration-tests/src/storage/write_object.rs]: delete, already handled in `run`

File: src/integration-tests/tests/driver.rs [hunk 3]
```diff
@@ -225,6 +225,20 @@ mod driver {
         result
     }
 
+    #[test_case(Storage::builder(); "default")]
+    #[tokio::test(flavor = "multi_thread", worker_threads = 1)]
+    async fn run_storage_repro(
```
Comment (dbolduc) [inline src/integration-tests/tests/driver.rs]: same, revert because already covered in `run_storage_write_object` ?

File: src/storage/src/storage/perform_upload/buffered.rs [hunk 4]
```diff
@@ -118,6 +118,7 @@ where
         progress: &mut InProgressUpload,
     ) -> Result<reqwest::RequestBuilder> {
         let range = progress.range_header();
+        tracing::info!("  ***** range={range} progress={progress:?}");
```
Comment (dbolduc) [inline src/storage/src/storage/perform_upload/buffered.rs]: revert debug logging

File: src/storage/src/storage/perform_upload/buffered/progress.rs [hunk 5]
```diff
@@ -164,6 +164,7 @@ impl InProgressUpload {
             (0, 0, Some(len)) => format!("bytes */{len}"),
             (0, 0, None) => "bytes */0".to_string(),
```
Comment (dbolduc) [inline src/storage/src/storage/perform_upload/buffered/progress.rs]: nit: seems like we can remove this for the general `(0, o, None)` case.

**Review by dbolduc — COMMENTED** [review]
The fix is good, but the PR needs some clean ups.

File: src/storage/src/storage/perform_upload/buffered/progress.rs (hunk 5 above)
Comment (coryan) [reply src/storage/src/storage/perform_upload/buffered/progress.rs]: Done.

File: src/integration-tests/src/storage.rs (hunk 1 above)
Comment (coryan) [reply src/integration-tests/src/storage.rs]: Uncommented.

File: src/integration-tests/src/storage/write_object.rs (hunk 2 above)
Comment (coryan) [reply src/integration-tests/src/storage/write_object.rs]: Removed.

File: src/integration-tests/tests/driver.rs (hunk 3 above)
Comment (coryan) [reply src/integration-tests/tests/driver.rs]: Removed.

File: src/storage/src/storage/perform_upload/buffered.rs (hunk 4 above)
Comment (coryan) [reply src/storage/src/storage/perform_upload/buffered.rs]: removed.
