### PR TITLE
fix(pubsub): change error return type for publish to Arc

### LINKED ISSUE #4619: Return Arc<Error> directly for publish results
The current implementation wraps all errors returned from a publish call into an Error::io. This obscures the actual error returned from the service. We want to resolve this by returning Arc<Error> directly.

### PR DESCRIPTION
**Pull request by suzmue**
To allow sharing the same crate::Error for multiple messages bundled in the same batch, we wrap the error in an Arc. This allows us to remove the code that wraps the originally Error in an Error::io.

The tests also needed to be updates since they were actually checking for the io error type.

Fixes #4619

### CODE REVIEW

File: src/pubsub/src/publisher/client.rs [hunk 1]
```diff
@@ -187,34 +187,43 @@ mod tests {
...
+        _options: gax::options::RequestOptions,
+    ) -> gax::Result<gax::response::Response<crate::model::PublishResponse>> {
+        Err(gax::error::Error::service(
+            gax::error::rpc::Status::default()
+                .set_code(gax::error::rpc::Code::Unknown)
                 .set_message("unknown error has occurred"),
         ))
     }
 
+    fn assert_publish_err(got_err: std::sync::Arc<gax::error::Error>) {
```
Comment (PhongChuong) [inline src/pubsub/src/publisher/client.rs]: nit. using fn to assert will not give the line number of test failure at the calling site.
I ended up using macro_rules! instead for test assert helpers.

Comment (dbolduc) [reply src/pubsub/src/publisher/client.rs]: There is also `#[track_caller]` for sync functions

https://github.com/googleapis/google-cloud-rust/blob/a00cd10164706eb8b8f4a8207409ff2bb31a156c/src/pubsub/src/subscriber/retry_policy.rs#L246-L253

Comment (suzmue) [reply src/pubsub/src/publisher/client.rs]: Oh nice! Thanks those are great workarounds.

I'll use track_caller here to keep things simple.
