### PR TITLE
fix(pubsub): return  error when publishing messages that are too large

### LINKED ISSUE #4650: Pubsub should return error when Publish message size is larger than batch threshold
The PubSub Publisher should return an error to the application when attempt to publish a message (including topic + ordering key) that has byte size greater than the configured batch size.

We should decide if we should also pause publishing when this error occurs (leaning no).

### PR DESCRIPTION
**Pull request by PhongChuong**
Publisher returns ExceededByteThresholdError when the application publish a message that is larger (with topic and ordering key) than the configured batch threshold.

For messages without ordering key, the Publisher returns an ExceededByteThresholdError for that message and continue as normal.
For messages with an ordering key, the Publisher returns an ExceededByteThresholdError for that message and pause publishing for the ordering key.

Fixes #4650

### CODE REVIEW

File: src/pubsub/src/publisher/batch.rs [hunk 1]
```diff
@@ -23,7 +23,7 @@ use std::sync::Arc;
 #[derive(Debug, Default)]
 pub(crate) struct Batch {
     messages: Vec<BundledMessage>,
-    initial_size: u32,
+    initial_size: u32, // TODO(NOW): Change this to topic instead.
```
Comment (dbolduc) [inline src/pubsub/src/publisher/batch.rs]: ?

File: src/pubsub/src/publisher/implementation.rs [hunk 2]
```diff
@@ -313,6 +313,67 @@ mod tests {
...
+        let key = "key";
+        let byte_threshold = TOPIC.len() + "hello".len() + key.len() + 1;
+        let publisher = PublisherPartialBuilder::new(client, TOPIC.to_string())
+            .set_byte_threshold(byte_threshold as u32)
+            .build();
+
+        // Validate without ordering key.
+        let handle = publisher.publish(Message::new().set_data("hello"));
+        assert_eq!(handle.await?, "hello");
+        let handle = publisher.publish(Message::new().set_data("too loooooooong"));
```
Comment (dbolduc) [inline src/pubsub/src/publisher/implementation.rs:334]: lol

File: src/pubsub/src/publisher/batch.rs (hunk 1 above)
Comment (PhongChuong) [reply src/pubsub/src/publisher/batch.rs]: Removed. Sorry I sometimes leave TODOs for revisit for the PR. I forgot to remove this one.
